# API Gateway Configuration
# Fetched from Config Server at startup

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Route to Task Service
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**

        # Route to User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

      # Global filters applied to all routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      # CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
