# Task Service Configuration
# Fetched from Config Server at startup

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Feign logging
logging:
  level:
    com.example.taskservice.client: DEBUG
